# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.3
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/node-auth-server

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - node-auth-server-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - node-auth-server-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: node-auth-server-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/node-auth-server
          paths:
            - config
            - controllers
            - middleware
            - models
            - routes
            - scripts
            - services
            - appspec.yml
            - index.js
            - package.json
            - package-lock.json
            - yarn.lock
      # run code quality!
      - run: yarn lint

  deploy-AWS:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/node-auth-server

    codedeploy:
      node_auth_server:
        application_root: /
        region: ap-south-1
        revision_location:
          revision_type: S3
          s3_location:
            bucket: nodejs-auth-server
            key_pattern: node-auth-server-{BRANCH}-{SHORT_COMMIT}
        deployment_group: nodejs-auth-server

    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/node-auth-server

      - run:
          name: Install AWS CLI
          command: sudo pip install awscli

      # - run:
      #     name: Configure CLI
      #     command: aws configure 

      # - run:
      #     name: Deploy to AWS S3
      #     command: aws deploy push --application-name nodejs-auth-server --s3-location s3://nodejs-auth-server/auth-server.zip --ignore-hidden-files --source ~/node-auth-server

workflows:
  version: 2
  build-deploy-app:
    jobs:
      - build
      - deploy-AWS:
          requires:
            - build
          filters:
              branches:
                only: master